name: Build nightly

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc
    name: Compile ROM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build GRRLIB
        run: |
          cd GRRLIB/
          dkp-pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo ppc-libvorbisidec ppc-mxml
          make -C GRRLIB clean all install
      - name: Make application
        run: |
          make -j4
      - name: Prepare for build publishing
        run: |
          mkdir -p out/rom
          mkdir -p out/rom/resources
          mkdir -p out/rom/resources/songs
          mkdir -p out/rom/user_levels
          mkdir -p out/rom/user_songs
          echo "Download the Geode mod loader and install the mod called GDShare, this mod adds a button to the level screen that exports the level to the .gmd file format. Add it in the folder where this .txt file is at for it to appear in Wii Dash." >> out/rom/user_levels/ADD_GMDs_HERE.txt
          echo "Go to %localappdata%/GeometryDash and put the .mp3 file with the file name of the \"<song_id>.mp3\", where <song_id> is the custom song id that the level uses, to the folder this .txt file is at." >> out/rom/user_songs/ADD_MP3s_HERE.txt
          cp -r data/hbc/. out/rom/
          cp -r data/songs/. out/rom/resources/songs/
          cp wiidash.dol out/rom/boot.dol
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: out/rom
          name: wiidash
